### ISSUE TITLE
Error on auth

### ISSUE THREAD

**Issue by iJayscn** [hlf20010508/telegram-onedrive#12]
容器提示：
Traceback (most recent call last):
  File "server/auth_server.py", line 62, in <module>
    port = int(server_uri.split(':')[-1].split('/')[0])
ValueError: invalid literal for int() with base 10: ''

直接访问：
https://ffffff.com (nagix proxy 反代)

当前无法使用此页面 https://ffffff.com 当前无法处理此请求。
HTTP ERROR 503

docker-compose.yml
```
version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    ports:
       - 8082:8082
    volumes:
      - /docker/tod:/tod
    # If you're on Linux, use this:
    #network_mode: host
    # If you're on Windows or macOS, use this, "xxxx" is your port in server_uri:
    

    # volumes:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key
      # - telegram-onedrive-session:/telegram-onedrive/session

    environment:
      - server_uri=https://ffffff.com (nagix proxy 反代)
      - tg_bot_token=XXXXX
      - tg_api_id=XXXX
      - tg_api_hash=XXXXX
      - tg_user_phone=+1XXXXX
      - tg_user_name=XXXX
      - od_client_id=XXXXX
      - od_client_secret=XXXXXX
      - remote_root_path=/tod
      - delete_flag=false
    command: python main.py

# volumes:
#   telegram-onedrive-session:
```

**Comment by hlf20010508** [comment]
我有说明必须要指明端口号的呀

**Comment by hlf20010508** [comment]
`server_uri`里

**Comment by hlf20010508** [comment]
我没有给反代适配过，目前只能通过volumes使用ssl

**Comment by hlf20010508** [comment]
我之后会考虑加一个`server_port`参数来应对反代的情况

**Comment by iJayscn** [comment]
> 我之后会考虑加一个`server_port`参数来应对反代的情况

直接通过VPS的IP:8882访问也是 

HTTP ERROR 503


我的docker-compose.yml 这么写没错吧，environment 段实际也都有填写

TG发送 /auth 可以收到 code ,但就是网页端打不开

**Comment by hlf20010508** [comment]
那你需要指定`server_uri`的端口号

**Comment by hlf20010508** [comment]
`https://ffffff.com:8082`

**Comment by iJayscn** [comment]
> 那你需要指定`server_uri`的端口号

改成IP授权成功

但是 上传不了
`Attempt 1 at connecting failed: TimeoutError: [Errno 110] Connect call failed ('91.108.56.100', 443)
Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
Getting difference for channel updates 1430957059 caused ValueError; ending getting difference prematurely until server issues are resolved
Attempt 2 at connecting failed: TimeoutError: [Errno 110] Connect call failed ('91.108.56.100', 443)`

**Comment by hlf20010508** [comment]
你这个错误我没见过。
不过有时候telegram确实会有timeout或者reset by peer的情况。
这个是telethon或者telegram服务器的问题。
如果不影响使用的话，无视就好。

**Comment by hlf20010508** [comment]
不应该呀，按理来说能传所有的。
后台有什么报错信息吗？
或者你换些资源试试也有这种情况吗？

**Comment by iJayscn** [comment]
> 不应该呀，按理来说能传所有的。 后台有什么报错信息吗？ 或者你换些资源试试也有这种情况吗？

日志正常，无报错。

你试下：https://t.me/ztods/33

**Comment by hlf20010508** [comment]
还真是。
我研究下。

**Comment by iJayscn** [comment]
> 还真是。 我研究下。

**Comment by hlf20010508** [comment]
不知道怎么回事，我只有第一次的时候是不能下载到视频的。
后面无论怎么弄都是可以的。
很奇怪。
但是感觉问题不大。

**Comment by hlf20010508** [comment]
新版发布了。
```yml
version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    ports:
       - 8082:8080

    ...

    environment:
      - server_uri=https://ffffff.com
      - reverse_proxy=true
```

在你的反代里面代理`http://127.0.0.1:8082`即可。

**Comment by iJayscn** [comment]
> 新版发布了。
> ```yml
> version: '3'
> services:
>   telegram-onedrive:
>     container_name: telegram-onedrive
>     image: hlf01/telegram-onedrive
>     restart: always
>     ports:
>        - 8082:8080
> 
>     ...
> 
>     environment:
>       - server_uri=https://ffffff.com
>       - reverse_proxy=true
> ```
> 
> 在你的反代里面代理`http://127.0.0.1:8082`即可。

好的   明天试下。这个程序真的好用
希望可以持续更新

**Comment by iJayscn** [comment]
> 新版发布了。
> ```yml
> version: '3'
> services:
>   telegram-onedrive:
>     container_name: telegram-onedrive
>     image: hlf01/telegram-onedrive
>     restart: always
>     ports:
>        - 8082:8080
> 
>     ...
> 
>     environment:
>       - server_uri=https://ffffff.com
>       - reverse_proxy=true
> ```
> 
> 在你的反代里面代理`http://127.0.0.1:8082`即可。


新版这个错误是啥意思？

Traceback (most recent call last):
  File "/telegram-onedrive/modules/handlers/auth.py", line 113, in auth_handler
    _tg_client = await tg_client.start(tg_user_phone, code_callback=tg_code_callback, max_attempts=tg_login_max_attempts)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 184, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in call
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 67, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/requeststate.py", line 17, in init
    self.data = bytes(request)
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 194, in bytes
    return self._bytes()
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/functions/auth.py", line 641, in _bytes
    self.serialize_bytes(self.phone_number),
  File "/usr/local/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 112, in serialize_bytes
    raise TypeError(
TypeError: bytes or str expected, not <class 'NoneType'>

**Comment by hlf20010508** [comment]
`docker-compose.yml`没写全吧？
你得补全呀。

**Comment by iJayscn** [comment]
> `docker-compose.yml`没写全吧？ 你得补全呀。

全的

```
version: '3'
services:
  telegram-onedrive:
    container_name: t2d
    image: hlf01/telegram-onedrive
    restart: always
    # If you're using reverse proxy, use this, "xxxx" is the port you want to be used in your reverse proxy:
    ports:
      - 8883:8080
    volumes:
      - /docker/t2d/Ox/tg-other:/Ox/tg-other

    # If you're on Linux, and not using reverse proxy, use this:
    # network_mode: host

    # If you're on Windows or macOS, and not using reverse proxy, use this, "xxxx" is your port in server_uri:
    # ports:
    #   - xxxx:xxxx
    
    # If you're using reverse proxy, use this, "xxxx" is the port you want to be used in your reverse proxy:
    # ports:
    #   - xxxx:8080

    # volumes:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key
      # - telegram-onedrive-session:/telegram-onedrive/session

    environment:
      - server_uri=https://*************:8883
      - reverse_proxy=ture
      - tg_bot_token=*************
      - tg_api_id=*************
      - tg_api_hash=*************
      - tg_user_phone=+*************
      - tg_user_name=*************
      - od_client_id=*************
      - od_client_secret=*************
      - remote_root_path=/Ox/tg-other
      # - delete_flag=$delete_flag(optional, true or false, default to false)
    command: python main.py

# volumes:
#   telegram-onedrive-session:
```
